#!/bin/bash


## search the web from the command line

BROWSER='firefox'
OPEN_IN='new window'
BASEURL='https://www.duckduckgo.com/?q='
SEARCH_TERM_SOURCE="command line"
while getopts :agdmiysvwWTGFKx OPT; do
    case $OPT in
        a|+a)
            BASEURL='http://adsabs.harvard.edu/cgi-bin/nph-basic_connect?qsearch='
            ;;
        g|+g)
            BASEURL='https://www.google.nl/#q='
            ;;
        d|+d)
            BASEURL='https://www.duckduckgo.com/?q='
            ;;
        m|+m)
            BASEURL='http://maps.google.com/maps?q='
            ;;
        i|+i)
            BASEURL='https://www.google.nl/search?hl=en&site=imghp&tbm=isch&q='
            ;;
        y|+y)
            BASEURL='https://www.youtube.com/results?search_query='
            ;;
        v|+v)
            BASEURL='http://translate.google.nl/#nl|en|'
            ;;
        s|+s)
            BASEURL='http://scholar.google.nl/scholar?q='
            ;;
        w|+w)
            BASEURL='http://en.wikipedia.org/wiki/'
            ;;
        T|+T)
            OPEN_IN='new tab'
            ;;
        W|+W)
            OPEN_IN='new window'
            ;;
        G|+G)
            BROWSER='chromium'
            ;;
        F|+F)
            BROWSER='firefox'
            ;;
        K|+K)
            BROWSER='konqueror'
            ;;
        x|+x)
            SEARCH_TERM_SOURCE="x selection"
            ;;
        *)
            echo "usage: ${0##*/} [+-agmiysvwWTGF} [--] SEARCH TERM..."
            exit 2
    esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

case $SEARCH_TERM_SOURCE in
    "command line")
        SEARCH_TERM="$*"
        ;;
    "x selection")
        SEARCH_TERM=$(xclip -o)
        ;;
    *)
        exit 1
esac

BROWSER_ARGS=""
if [[ $BROWSER == 'chromium' ]] ; then 
    if [[ $OPEN_IN == 'new window' ]] ; then 
        BROWSER_ARGS="$BROWSER_ARGS --new-window"
    fi
elif [[ $BROWSER == 'firefox' ]] ; then
    if [[ $OPEN_IN == 'new window' ]] ; then 
        BROWSER_ARGS="$BROWSER_ARGS -new-window"
    elif [[ $OPEN_IN == 'new tab' ]] ; then 
        BROWSER_ARGS="$BROWSER_ARGS -new-tab"
    fi
fi

COMMAND="$BROWSER $BROWSER_ARGS \"$BASEURL${SEARCH_TERM}\""
bash -c "$COMMAND"
